spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false
        show_sql: false

  jwt:
    secret: ${spring.jwt.secret}
    access_expiration: 86400000
    refresh_expiration: 86400000

# AWS S3
cloud:
  aws:
    region: ${cloud.aws.region}
    s3:
      bucket: ${cloud.aws.s3.bucket}
    stack:
      auto: false
    credentials:
      access-key: ${cloud.aws.credentials.access-key}
      secret-key: ${cloud.aws.credentials.secret-key}

logging:
  level:
    root: info